### ISSUE TITLE
希望增加的几个功能吗?

### ISSUE THREAD

**Issue by Theergold** [Frederisk/Wikitext-VSCode-Extension#1]
1.希望增加十六进制颜色代码的对应颜色高亮渲染
2.希望增加连接的高亮

**Comment by Frederisk** [comment]
對於問題一：我需要更加詳細的說明或者例子來確信是在何種狀態下需要這樣的渲染效果。

對於問題二：一個正確的連結VSCode理應會以下劃線標注，對於外部連結\[https:\//example.test Test\]其前方的連結也會默認以下劃線標注，特別地，類似\[wrong.ex foo\]丟失HTTP前綴的連結在MediaWiki中是非法的，所以它們理應不被渲染標記（不過為了突出錯誤，它們在外部連結語法中會被渲染為錯誤警告色（通常是紅色））。

**Comment by Theergold** [comment]
``` text
幸运儿現在总共有6件时裝(不算初始那套),分为:
* {{color|#FFA500|稀世时装(0件)。}}
* {{color|#6633CC|珍奇时装(2件):女仆装、双一。}}
* {{color|#1E90FF|独特时装(2件):月亮脸、雅典异乡人、疯狂的耿浩。}}
* {{color|#008000|罕见時裝(1件):棕。}}
```

![](https://i.loli.net/2020/03/09/Z83FVRsToPdjIqC.png)

个人认为为了方便在写作过程中确定得出出来的文段的颜色,可以再将上文的color语句中的十六进制颜色代码渲染为对应的颜色方便写作

**Comment by Frederisk** [comment]
我考慮了該意見，但是最後決定不予更改，理由是#32位元RGB並非Mediawiki規範Wikitext中的標準定義表達式，而且加入該渲染模式可能會導致不必要的誤會或者渲染問題。

作為替代，你可以使用Visual Studio Market上的Color Picker或者VS Color Picker作為替代來使色彩輸入更為便捷，最後感謝你的建議。

如果你沒有其他問題，該issue將會被關閉。
