### ISSUE TITLE
Add the function of quick citation to references.

### ISSUE THREAD

**Issue by jasonwilliams** [Frederisk/Wikitext-VSCode-Extension#12]
I saw this on your todo list.

How do you plan to implement this?
mediaWiki uses https://github.com/jasonwilliams/mediawiki-support/blob/master/src/webCitation.ts you're free to take a copy of that as a start.

Calling webArchive is useful as wikipedia expects users to do this anyway, so the fact that it's automatic helps.

**Comment by Frederisk** [comment]
I'm sorry I have been very busy in the past two months so I didn't set out to add this feature.

I recently got a short break. After finishing my previous task and solving some pressing issues, I will start working on it.

And Thanks for your help. Your code is very helpful to me. I will try to release it before the end of December.🐱‍💻
