### ISSUE TITLE
[Enhancement] Lua syntax highlighting support for scribunto modules

### ISSUE THREAD

**Issue by Thundercraft5** [Frederisk/Wikitext-VSCode-Extension#18]

**Comment by Frederisk** [comment]
I don't quite understand. If you want Lua syntax support, you should choose Lua in the language option in the lower left corner, right?

**Comment by Frederisk** [comment]
Since there is no further description, this issue will be closed. If you think this issue is still worth discussing, please describe your thoughts in detail or go to the [discussion page](https://github.com/Frederisk/Wikitext-VSCode-Extension/discussions).

**Comment by GarliC-C** [comment]
> I don't quite understand. If you want Lua syntax support, you should choose Lua in the language option in the lower left corner, right?

Yes, but when pulling the Lua page, the pageinfo at the top will cause confusion in the code recognition of the Lua editor. I tried to add  「--」 before the pageinfo. Although it does not affect the post function, the upload result will cause the first line of code to be annotated.

**Comment by Frederisk** [comment]
> > I don't quite understand. If you want Lua syntax support, you should choose Lua in the language option in the lower left corner, right?
> 
> Yes, but when pulling the Lua page, the pageinfo at the top will cause confusion in the code recognition of the Lua editor. I tried to add  「--」 before the pageinfo. Although it does not affect the post function, the upload result will cause the first line of code to be annotated.

@GarliC-C This sounds weird, can you open another issue to describe the problem in more detail? I actually had an improvement on this a few versions ago. But according to your description, it doesn't seem to work properly.

**Comment by GarliC-C** [comment]
Well, I'm using version 3.4 because my wiki project doesn't support logging in to the latest plug-in version...

**Comment by GarliC-C** [comment]
> > > I don't quite understand. If you want Lua syntax support, you should choose Lua in the language option in the lower left corner, right?
> > 
> > 
> > Yes, but when pulling the Lua page, the pageinfo at the top will cause confusion in the code recognition of the Lua editor. I tried to add  「--」 before the pageinfo. Although it does not affect the post function, the upload result will cause the first line of code to be annotated.
> 
> @GarliC-C This sounds weird, can you open another issue to describe the problem in more detail? I actually had an improvement on this a few versions ago. But according to your description, it doesn't seem to work properly.

Well, I'm using version 3.4 because my wiki project doesn't support logging in to the latest plug-in version...
