### ISSUE TITLE
Feature Request: Optional variable for unsecure traffic.

### ISSUE THREAD

**Issue by Rina-Y** [Frederisk/Wikitext-VSCode-Extension#19]
Curious if there was a way to have this extension have a setting to allow for http traffic rather than https.  I have a couple mediawiki's that do not run on https yet and another that does not have a domain name (it is currently running straight from IP address).  It would be nice if I could have it not fail in these situations due security being less than optimal.

**Comment by Frederisk** [comment]
This is currently unchangeable, but I will try to add this optional item in the future.

**Comment by Frederisk** [comment]
This function has been added, you can build the solution yourself according to the instruction on the README file, then install the extension and test this function.

If there are any problems, please open a new issue.
