### ISSUE TITLE
[Enhancement] Template styling in Preview and Preview for mobile devices needed

### ISSUE THREAD

**Issue by BrandNewJimZhang** [Frederisk/Wikitext-VSCode-Extension#21]
Great work bro, I'm dreaming all day and night thinking about writing an editor with wikitext rendering and preview😂, but there's still something to do next:

1. ![image](https://user-images.githubusercontent.com/47765973/105063567-d3ddac80-5ab6-11eb-8775-569211df34c5.png)
   The preview page shows a [navbar](https://en.wikipedia.org/wiki/Template:Navbar), which uses [Lua script](https://en.wikipedia.org/wiki/Module:Navbox) (clearly that it's easy to rewrite in typescript or javascript) rendered on MediaWiki. (this is what #18 meaning bro) I think the styling can be enhanced like that. I thought I expressed clearly🙂...
   What English wikipedia rendered like: (**default collapsed and expanded also applyed**)
   ![image](https://user-images.githubusercontent.com/47765973/105066880-2ec4d300-5aba-11eb-9ef7-fcf465a478e9.png)
2. Templates like navbox won't be shown on mobile phones. But when we scratch the preview page (tab in vs code), if I'm a developer😂, I don't know whether the page should be responsive, for **those templates won't appear on mobile devices**.
3. Editing an article on wikipedia is like developing a website, **both display effects on desktop and mobile devices needed**. Here are my two contrast opinions for you to argue: First, this plugin should be easy to use, only desktop effect is ok. Another, both effects needed.
4. **CSS preference interface** is a future work, wikipedia supports personalized css. We can consider personal CSS preference interface for rendering. (Maybe then a documentation need lol)

Maybe I didn't express these opinions or issues clearing due to my poor English😔, if further explantion needed, please reply bro.

**Comment by Frederisk** [comment]
There are too many issues here, please split them into different issues in order to solve them one by one.

If you feel it's difficult to use English, you can try Chinese(中文) or Russian(русский).
