### ISSUE TITLE
Can we make the texts between <ref> and </ref> dimmed?

### ISSUE THREAD

**Issue by asthzh** [Frederisk/Wikitext-VSCode-Extension#29]
Can we make the texts between \<ref\> and \</ref\> dimmed? Just like wikEd does
The texts are so unrecognizable right now, especially when there are a lot of references
習慣用 vs code 編輯條目，找正文看到眼睛快瞎了

**Comment by Frederisk** [comment]
The extension will only tell VSCode what type of text is, not the color. The choice of color depends on the theme of VSCode.  There is no reliable way to specify a certain type of text so that the color of the text must be more dimmed than elsewhere.

I might try to make the plain text in the ref tags have a different type to distinguish it from the main text.(e.g. `<ref>BookName, ISBN 000</ref>`) But for templates and other types of text,(e.g. `<ref>{{template}}</ref>`)

At last but not the least, it's suggested for me that naming a ref and putting it in the references chapter of the article. This is a good writing practice. As follows:
``` wikitext
Hello<ref name="hello" />

== References ==
<references>
<ref name="hello">this is a hello</ref>
</references>
```

VSCode的語言拓展只是在指定某段特定文字的語法類別，並不是在指定顏色。某類型的文字要渲染成甚麼顏色取決於在VSCode用了甚麼主題。插件本身不能明確指定某種文字會被染成甚麼顏色的，也就沒法保障某段文字確實能染成比較暗的顏色。

我或許會試試指定給ref裡面的純文字內容有不同的類型，這樣就能和正文區分開，不過這種指定只限於ref中的純文本。（例子見上）

另外，個人確實推薦給ref命名然後放在參考資料一章。這樣便於閱讀和管理，我想對除了可視化編輯器之外的人來說都有好處吧。（例子見上）

**Comment by asthzh** [comment]
thank you for your reply and advice, but I'm mostly working on translations instead of creating new articles, that means that it would be much difficult for me to move all those references over just bear it and find texts between refs. So I'll just wait and see what you can do

**Comment by Frederisk** [comment]
I redefine the categories of some elements, including ref tags, and then launched a sample survey among some users, but the result is that many people seem to dislike this change. A better solution is to use a language server to make the text structure more explicit and provide some contextual support, but I don't have enough time to do so at present.

before:
![image_2021-05-28_23-55-05-l](https://user-images.githubusercontent.com/29837738/120062822-a91fe800-c096-11eb-8ff3-2193f14abb5b.png)

after:
![image_2021-05-28_23-55-05-r](https://user-images.githubusercontent.com/29837738/120062839-b50baa00-c096-11eb-89ab-9c589b8392e2.png)

**Comment by asthzh** [comment]
> I redefine the categories of some elements, including ref tags, and then launched a sample survey among some users, but the result is that many people seem to dislike this change. A better solution is to use a language server to make the text structure more explicit and provide some contextual support, but I don't have enough time to do so at present.
> 
> before:
> ![image_2021-05-28_23-55-05-l](https://user-images.githubusercontent.com/29837738/120062822-a91fe800-c096-11eb-8ff3-2193f14abb5b.png)
> 
> after:
> ![image_2021-05-28_23-55-05-r](https://user-images.githubusercontent.com/29837738/120062839-b50baa00-c096-11eb-89ab-9c589b8392e2.png)

Thank you for your work! So the changes are not going to publish right? It's fine by me because I've found a workaround for this which is to paste the source code then use the visual editor for contrasting.

**Comment by Frederisk** [comment]
Yes, it will be changed. That just means that __the default options__ will not be changed.

Here is an improvement method, I will define the content in ref as `meta.embedded.block.ref.wikitext` (tentative). After that, you can customize the colors you need through the `editor.tokenColorCustomizations` in the user settings.

How to do it:
![Annotation 2021-05-29 174303](https://user-images.githubusercontent.com/29837738/120065713-5dc10600-c0a5-11eb-9f35-7976349bb19c.png)

**Comment by Frederisk** [comment]
FYI:

- <https://code.visualstudio.com/docs/getstarted/themes#_editor-syntax-highlighting>
- <https://code.visualstudio.com/api/language-extensions/syntax-highlight-guide#scope-inspector>

**Comment by Frederisk** [comment]
> Yes, it will be changed. That just means that **the default options** will not be changed.
> 
> Here is an improvement method, I will define the content in ref as `meta.embedded.block.ref.wikitext` (tentative). After that, you can customize the colors you need through the `editor.tokenColorCustomizations` in the user settings.
> 
> How to do it:
> ![Annotation 2021-05-29 174303](https://user-images.githubusercontent.com/29837738/120065713-5dc10600-c0a5-11eb-9f35-7976349bb19c.png)

This effect has been adjusted separately, and the name of the range has been determined to be contentName: meta.embedded.block.ref.wikitext. In addition, you can even adjust this part to be transparent.

![Annotation 2021-05-29 174303](https://user-images.githubusercontent.com/29837738/120067515-aaf5a580-c0ae-11eb-9523-c379976fe7b7.png)
