### ISSUE TITLE
Logins to Internal Wiki

### ISSUE THREAD

**Issue by ceagan** [Frederisk/Wikitext-VSCode-Extension#32]
We have an internal wiki that uses Active Directory logins via MediaWiki's [LDAP Stack](https://www.mediawiki.org/wiki/LDAP_Stack) extension set that doesn't seem to work with this VSCode extension. Logins fail during attempts to preview.

It looks like some changes may be needed on the MediaWiki extension and the VSCode extension may have to specify `pluggableauthlogin=1` for the logins to work. I think this could be added as a boolean setting in the VSCode extension settings so that users could enable it as needed. [This thread](https://www.mediawiki.org/wiki/Topic:Waumast9zv441fyx) about login via the API with these extensions enabled that may be helpful in addressing this issue. I applied the patch linked in the thread and got past the first issue, but the logins still fail, possibly because of the need to specify `pluggableauthlogin=1`.

**Comment by Frederisk** [comment]
Sorry for my late reply due to busy work. I checked the discussion on the LDAP extension, and I noticed that you mentioned `action=clientlogin`, but in this extension, I used `action=login`. Have you tried using BotPassword.
