### ISSUE TITLE
command 'wikitext.getPreview' not found

### ISSUE THREAD

**Issue by ageovb** [Frederisk/Wikitext-VSCode-Extension#40]
When I click the **Preview** button, I get the error below：
`command 'wikitext.getPreview' not found`

VSCode version：1.62.3
Wikitext version：3.6.0

**Comment by Frederisk** [comment]
Please ensure that you workspace are trusted and try again. This problem can not be reproduced on my device.

**Comment by ageovb** [comment]
Thank you. The error disappeared after the computer was rebooted.
