### ISSUE TITLE
When copying text from VSCode it be pasted as HTML formatted text in Word

### ISSUE THREAD

**Issue by hubaishan** [Frederisk/Wikitext-VSCode-Extension#42]
When copying text from VSCode it be pasted as HTML formatted text in Word with black background as style of VSCode and same font and styling colors of VSCode. This happened only with (wikitext) type files on (plaintext) files text is  pasted as plain text.

**Comment by Frederisk** [comment]
I am not sure, but it seems a problem of your operation or a bug of your OS, or Word, or VSCode. The editor used by this extension is the same as another editors in VSCode.

If you want to past the text as plain into Word. Please

- right click on the page and select `Keep Text Only`, or
    ![image](https://user-images.githubusercontent.com/29837738/145550803-8b1c582b-2954-4740-9bf4-1ab5089a26c1.png)

- press `Ctrl + Alt + V`, then select `As: Unformatted Text` and click `OK`.
    ![image](https://user-images.githubusercontent.com/29837738/145550992-76dc0ce8-b7b8-4496-92ed-4d484a72448e.png)

Finally, if you can, please try to change to another version of VSCode (such as: Insiders Version), or update Word or system environment, which will help troubleshoot the cause of the problem.
