### ISSUE TITLE
Self-closing nowiki tags do not highlight properly.

### ISSUE THREAD

**Issue by jcdhan1** [Frederisk/Wikitext-VSCode-Extension#43]
The self-closing nowiki tag: `<nowiki />` is permissible [according to MediaWiki](https://www.mediawiki.org/wiki/Help:Formatting#Nowiki_for_HTML). In addition to the examples presented on that Help page, other usages of it include preserving leading spaces after pipes  | in template and parser function calls.
`{{Some template|Some parameter=<nowiki /> this value will have a space before it}}`

Example of how highlighting it should work (Fandom's Wikitext editor):
![image](https://user-images.githubusercontent.com/709117/145478897-3bc3f284-1103-451e-a9ef-335cbea5f4b0.png)

What the Wikitext-VSCode-Extension currently does is treat it like a opening nowiki tag so all code after it is not highlighted until there is a closing nowiki tag.
![image](https://user-images.githubusercontent.com/709117/145486247-665b2efc-6806-4807-9bfd-3132eb822232.png)

**Comment by Frederisk** [comment]
Ref: #44
