### ISSUE TITLE
MediaWiki redirects

### ISSUE THREAD

**Issue by nedevel** [Frederisk/Wikitext-VSCode-Extension#5]
MediaWiki supports page redirects using `#REDIRECT`. Could this be highlighted for completeness in the syntax file?

**Comment by lmn8** [comment]
Following [Textmate naming conventions](https://macromates.com/manual/en/language_grammars#naming_conventions), I think the redirect should be highlighted as `keyword.control`. To differentiate from the existing behaviour switches (currently listed as the `"keywords"` key), those should be highlighted as `constant.language` instead.

**Comment by Frederisk** [comment]
It seems that I have missed this very important thing, and I will further consider other magic words. Your suggestion about Textmate is very valuable and it will be adopted.
