### ISSUE TITLE
There are always extra `"` in the preview

### ISSUE THREAD

**Issue by HubKing** [Frederisk/Wikitext-VSCode-Extension#54]
If I understood it correctly, the preview feature is sending the Wiki markup to Wikipedia server, retrieve the HTML, and display it in VS Code; is that right? If so, how about adding "Show source" in the context menu (or any other way)? I think it would be helpful to understand the structure.

Also, the preview shows a line with `"` at the beginning no matter what the input is. Isn't it a bug?

![image](https://user-images.githubusercontent.com/10900489/151402855-bdf012dc-ca0a-43e2-9144-45369595117a.png)

**Comment by Frederisk** [comment]
> Also, the preview shows a line with " at the beginning no matter what the input is. Isn't it a bug?

You are right, I added an extra `"` symbol to the string by mistake.

> how about adding "Show source" in the context menu (or any other way)?

VSCode is developed by Electron, which is based on Chromium. So, like most browsers such as Chrome or Edge you know, you can press `Ctrl+Shift+I` or open the Developer Tools in `Help` to view the source code of webview:

![image](https://user-images.githubusercontent.com/29837738/151665392-871fe6d0-6aca-4000-b595-6baa1ab9afaf.png)

**Comment by HubKing** [comment]
Actually, I had tried that developer tool, but it was not convenient because I had to find the Wiki view's node. Don't you get some sort of string response from Wikipedia's server? I think it would be a lot easier to see if that raw source string was opened in a new tab or something.

**Comment by Frederisk** [comment]
I don't find this difficult. You just need to find `class="mw-parser-output"`.🤔
