### ISSUE TITLE
Error when pushing changes

### ISSUE THREAD

**Issue by jcdhan1** [Frederisk/Wikitext-VSCode-Extension#57]
## Replication steps

1. Configure Wikitext-VSCode-Extension for any wiki on fandom.com
2. Log in.
3. Pull or create a page.
4. Make an edit.
![image](https://user-images.githubusercontent.com/709117/154354326-595ce1b7-8f9d-4d72-a8db-64a7c8408128.png)
5. Push the edit.
![image](https://user-images.githubusercontent.com/709117/154354460-c7075116-c05f-494b-8f6e-ec7ffa1771aa.png)
6. Enter an edit summary (optional).
![image](https://user-images.githubusercontent.com/709117/154354522-906a00c5-283e-44d7-8b54-6bf7b7f0bcc9.png)
7. Hit the enter key:
    + Expected: Edit is successfully saved.
    + Actual: Edit is not saved and there is an error.
![image](https://user-images.githubusercontent.com/709117/154354762-49a33fcb-306c-4218-8957-31cfab4e5439.png)

## Investigation
Since v3.6.3, this error happens when pushing to any fandom.com wiki:

```EOF
'Invalid value for key "name". Expected type "" but got 0'
```

It doesn't happen when downgrading to v3.6.2.

The commit has been bisected to 1fecc623986ed61ba5d85d217bce1d6f53cf1604. The tag interface added in that commit mandates the property ``name`` of type ``string``.

```typescript
export interface Tag {
    name: string;
    defined?: string;
    active?: string;
}
```

Most of the objects in ``query.tags`` obey this.

But some of them have ``name`` be of type ``number``.

```typescript
{name: 0} // query.tags[4]
{name: 1} // query.tags[26]
{name: 2} // query.tags[27]
{name: 3} // query.tags[28]
```

The problem seems to be one of the transform methods in convertFunctions.ts. When the name has a numeric value, the object is not cast properly or at all.

**Comment by Frederisk** [comment]
Thanks for the detailed description of the issue, it was extremely helpful for me to solve it. I've tried to fix the issue, but I can't test it right away because my sysop permission on the publictestwiki have expired. Can you compile it yourself and report back the results?

**Comment by jcdhan1** [comment]
> Thanks for the detailed description of the issue, it was extremely helpful for me to solve it. I've tried to fix the issue, but I can't test it right away because my sysop permission on the publictestwiki have expired. Can you compile it yourself and report back the results?

Yeah, it works as expected now. I tested on two different Wikis.
![image](https://user-images.githubusercontent.com/709117/154773868-69d0a1fb-619e-4ef5-b34b-7b274866e40f.png)
