### ISSUE TITLE
can't pull page

### ISSUE THREAD

**Issue by GarliC-C** [Frederisk/Wikitext-VSCode-Extension#59]
![image](https://user-images.githubusercontent.com/46807952/164888541-e013d4aa-daf9-418c-bdfe-f53c6c14a0fc.png)

`ErrorName: Error; ErrorMessage: Invalid value {"main":{"*":"Unrecognized parameter: rvslots."}} for type [null,{"ref":"MWError"}];`

I don't know if it's helpful, but I'm here to provide my MediaWiki project website:r6s.huijiwiki.com/api.php

In fact, in version 3.4, I will modify the content of user agent to achieve normal operation (change "mwbot" to my own user name)

like this：
extension.js
![image](https://user-images.githubusercontent.com/46807952/164889307-340ef3e8-fb04-4e3b-a8c3-b72b70589dfb.png)

**Comment by Frederisk** [comment]
It looks like it's just caused by an outdated MediaWiki version. the parameter `rvslots` is introduced in v1.32 but you have is v1.30. I might consider providing compatibility with older versions, but I would recommend you to update the version of MediaWiki if you can.

**Comment by GarliC-C** [comment]
> It looks like it's just caused by an outdated MediaWiki version. the parameter `rvslots` is introduced in v1.32 but you have is v1.30. I might consider providing compatibility with older versions, but I would recommend you to update the version of MediaWiki if you can.

OK, our wiki farm is planning to upgrade to 1.38, and I will continue to feed back if there are any questions later.
