### ISSUE TITLE
Wikimedia Two-factor_authentication

### ISSUE THREAD

**Issue by pixiandouban** [Frederisk/Wikitext-VSCode-Extension#66]
If Two-factor_authentication (2FA) is enabled, VS Code can't log in Wikipedia. Is there a better way to login, turn off 2FA, activate 2FA login?

**Comment by Frederisk** [comment]
Use [Bot Password](https://www.mediawiki.org/wiki/Manual:Bot_passwords) instead.

**Comment by pixiandouban** [comment]
Thanks, I tried and it works.
