### ISSUE TITLE
Add basic authentication to settings.

### ISSUE THREAD

**Issue by Hansi132** [Frederisk/Wikitext-VSCode-Extension#69]
Currently there is no posibility to edit a webpage that is behind basic authentication.

Solution to this would be to add a setting for username and password for basic authentication when performing calls to the wikipage host.

**Comment by Frederisk** [comment]
I don't particularly understand. Password and username login functionality should be available. For some private sites, you need to log in first using `Wikitext: Login with your account` to pull pages.

**Comment by Hansi132** [comment]
Hi. Forgot to resolve this. The site i was trying to access used basic authentication that could be resolved in the url.
username:password@url.com.

The plugin is really nice to use.

**Comment by Frederisk** [comment]
Oh, I see. So this problem has been solved, right? Then I will close it.😸
