### ISSUE TITLE
"Read page to edit" should support "login with your account"

### ISSUE THREAD

**Issue by djradon** [Frederisk/Wikitext-VSCode-Extension#7]
For non-public wikis (i.e.,$wgGroupPermissions['*']['read'] = false) it'd be great if you could use the current login credentials to retrieve a page for editing. Right now I believe it just fails silently.

**Comment by Frederisk** [comment]
I have understood the problem, but this change may be a major change that affects many existing functional logic. I need some time to modify the main logic of accessing the API. Currently it depends on the npm package `wmbot` whos function is limited.

**Comment by djradon** [comment]
Thanks for the response. Do you do Patreon or one of the other sponsorship platforms?

**Comment by Frederisk** [comment]
I am very happy that you are willing to provide me with some financial assistance.❤ I do have a [Patreon account](https://www.patreon.com/rwfholme), but I have hardly used it(I only use it to donate to others but not myself).

**Comment by Frederisk** [comment]
The problem should be resolved in the latest version (3.1.0 or later), ￼give it a try!

**Comment by JeremiPlazas** [comment]
Hi there, sorry to reopen something that seemed resolved. I manage multiple wikis, some open some private (via same `$wgGroupPermissions['*']['read'] = false` setting as op). I'm not able to access pages on the private wikis. I get the following:

<img width="565" alt="Screen Shot 2022-04-29 at 2 43 02 PM" src="https://user-images.githubusercontent.com/4063437/166067264-f74e35af-bac7-4cfe-a5c8-f0ccd28c464b.png">

I have the login credentials setup in the extension settings. Working with MediaWiki 1.31.12.

Thanks for the attention

**Comment by Frederisk** [comment]
@JeremiPlazas Are you logged in to the extension?  Press `ctrl + shift + p` and enter `Wikitext:Login`.

**Comment by JeremiPlazas** [comment]
Thanks for the prompt reply. I wasn't and logged in as you suggested. Now getting the following error:
<img width="559" alt="Screen Shot 2022-04-30 at 2 34 31 PM" src="https://user-images.githubusercontent.com/4063437/166121774-e7828de1-4dc6-489b-bbd5-666bdd57bb97.png">

**Comment by JeremiPlazas** [comment]
Also the logging in presents another problem as I manage and develop over 10 wikis, all with different credentials. Hence my upvote for [multi-site support](https://github.com/Frederisk/Wikitext-VSCode-Extension/issues/34#issue-997509246) (a la [Sublime text](https://github.com/tosher/Mediawiker)).

**Comment by Frederisk** [comment]
@JeremiPlazas This is due to the MediaWiki version. Refer #59.

**Comment by JeremiPlazas** [comment]
Ah, thank you! That’s it.
