### ISSUE TITLE
Bracket highlighting not working in v3.7.0

### ISSUE THREAD

**Issue by DevarooGit** [Frederisk/Wikitext-VSCode-Extension#70]
G'day, thanks for this very useful extension. FYI, in v.3.7.0 bracket highlighting doesn't work at all on my machine. Nada, niente. In v.3.6.5 it works 99% fine; only issue is that highlighting of some closing brackets is delayed. I'm currently using the extension with VS Code 1.74.0 with macOS Catalina (10.15.7). If you need more information please let me know. Cheers, Lucas

**Comment by Frederisk** [comment]
Due to some API technical limitations, I can't control the correct rendering of bracket highlighting, so I disabled this feature in the latest version. I'm thinking of some other countermeasures to improve the problem.

Also, I've noticed that some themes may not render editor tokens correctly. But the default Dark+ theme is ok, if it doesn't have any highlight on some popular theme, please let me know.

**Comment by Frederisk** [comment]
Another solution is to use the previous solution, adding highlighting to each parenthesis. I'm wondering if you think it's better to use a scheme like this as shown in the picture (which might make the display too fancy), or would you rather have no highlighting?

![image](https://user-images.githubusercontent.com/29837738/209460757-f8b53110-625c-420d-88dd-4c8ad7e9974a.png)

PS: Just an investigation and may not end up selecting these options.

**Comment by shaedrich** [comment]
Is this just about syntax highlighting in general, or about matching bracket pairs? Because, especially in wikitext where you can't have indention and stuff, I really need to find bracket pairs quickly in large templates.

**Comment by Frederisk** [comment]
Yes, I mean the matching of paired parentheses.

**Comment by DevarooGit** [comment]
> Another solution is to use the previous solution, adding highlighting to each parenthesis. I'm wondering if you think it's better to use a scheme like this as shown in the picture (which might make the display too fancy), or would you rather have no highlighting?

No, highlighting single brackets isn't helpful. The ideal solution is something like this:

<img width="1059" alt="VS-Studio-Code-Wikitext-Bracket-Highlighting" src="https://user-images.githubusercontent.com/118488203/211194727-c94dbdbb-6a99-4377-9e95-f7a19446dd3d.png">

This solution (1) matches double curly braces (templates) as well as triple curly braces (parameters) and (2) uses different colors if templates or paremeters are nested. Which happens to be what I get with Wikitext extension v3.6.5, running on VC 1.74.0 for macOS 10.15.7.

**Comment by Frederisk** [comment]
The problem is that such highlights will render incorrectly in many edge cases:

```wikitext
{{t|{{#if:|}}}}
```

Some people complain about wrong rendering like this.

**Comment by DevarooGit** [comment]
/offtopic start

> Especially in wikitext where you can't have indention

If indentation is giving you trouble, I would recommend to still write clean code in VC Code – i.e., with appropriate line breaks and indents – and then save a copy with all line breaks and indents removed for use in MediaWiki. This can easily be done in VC Code by selecting all code and pressing `ctrl`+`j` (on mac, don't know what the Windows hotkey is). This is incredibly useful even when you have bracket highlighting. BTW, I've found that indentation actually does work well in most cases (MW 1.38 / 1.39); but yeah, there's the odd case where it doesn't work. In those cases I would use the method described above.

/offtopic end

**Comment by DevarooGit** [comment]
> The problem is that such highlights will render incorrectly in many edge cases:
> 
> ```
> {{t|{{#if:|}}}}
> ```

This isn't really an edge case, it's simply a nested template where two or more closing brackets are right next to each other (i.e., without other characters between them). (In this case it's a parser function nested inside a template, but given that a parser function also has 2 curly braces at its start and end, I assume that won't make a difference?).

Anyway, users can fix the issue that you show by adding a space between the closing brackets:

<img width="253" alt="Screenshot 2023-01-08 at 13 40 43" src="https://user-images.githubusercontent.com/118488203/211196571-5110d6ca-1b98-4270-a414-2fb5025ae664.png">

Another way to fix this is adding line breaks before parameters:

<img width="155" alt="Screenshot 2023-01-08 at 13 40 44" src="https://user-images.githubusercontent.com/118488203/211196580-fd869508-44c1-4d50-baf8-3867103521e1.png">

I've found that both solutions work well in most cases, i.e. they won't break wikitext functionality.

I would agree that _not_ having to use such workaround would be even more convenient. But for me personally it's acceptable. Especially since using linebreaks is often the cleanest solution anyway (see my previous response to @shaedrich). In any case, using this very small workaround is imho preferable to not having bracket matching at all.

**Comment by Frederisk** [comment]
OK, I'll take your opinion. And try to restore this functionality in a future minor version update.

**Comment by DevarooGit** [comment]
Sounds good, thanks mate! If necessary, feel free to adapt my previous response for the documentation, e.g. for a section "Known issues". Greetings and have a nice evening
