### ISSUE TITLE
Commands resolving to Not Found

### ISSUE THREAD

**Issue by T2ThatGuy** [Frederisk/Wikitext-VSCode-Extension#76]
In version 3.8.0 _Released a few hours ago_. You can't run the command Get Preview as it responds with the error

Command 'Wikitext: Get preview' resulted in an error (command 'wikitext.getPreview' not found)

This appears to also be true with the other commands in this version too.

**Comment by Frederisk** [comment]
Kind of weird, I've installed it separately on some of my devices and it's been fine.🤔

**Comment by Frederisk** [comment]
Can you tell me where you installed it from? VS Market? Maybe you can try removing and reinstalling it, or try installing from the `.vsix` file.

**Comment by T2ThatGuy** [comment]
I installed it from the VS Market in the App. So far I have tried, re opening both before and after installation uninstalling the extension and reinstalling it too. I will try to see if I can get it working on a different machine too. So far my current solution is just to downgrade to the previous version.

Where would I find the .vsix file?

**Comment by T2ThatGuy** [comment]
As it turns out, I was actually running an older version of VSCode on the laptop in question. It was running version 1.66 after updating to the most recent version it was working alright, on the latest version of the extension

**Comment by Frederisk** [comment]
Glad you were spotted the problem. By the way, you can find the installation files in [the release page of this repository](https://github.com/Frederisk/Wikitext-VSCode-Extension/releases/).
