### ISSUE TITLE
Treat `|}` as table closure only at start of line

### ISSUE THREAD

**Issue by jwfxpr** [Frederisk/Wikitext-VSCode-Extension#78]
Currently, the bracket highlighting treats `|}` as a special digraph, which is appropriate when handling tables. Wikitext tables are demarked by an opening `{|` and closing `|}`, which must be at the start of a line to be interpreted as a table.

These two characters also appear frequently in non-lua template code, especially when handling parameters in [parser functions](https://www.mediawiki.org/wiki/Help:Extension:ParserFunctions). E.g.,

```
{{#if:{{{1|}}}|First unnamed parameter has a value|First unnamed parameter has no value}}
```

This example evaluates to `First unnamed parameter has no value` if the first unnamed parameter has no value.

Currently, the extension will sometimes incorrectly interpret the `|}` here as a table closure, leading to incorrect and confusing bracket matching in templates which use this technique:

![image](https://github.com/Frederisk/Wikitext-VSCode-Extension/assets/20788820/cc145aa1-f84c-4213-9b3e-db019ec062fc)

The more complex the template, the more this error compounds, leading the extension to be counterproductive when handling the most complex templates (which is where it should be most relied upon).

Restricting the `|}` table closure symbol matching to the start of a line would eliminate this issue. 😊

**Comment by Frederisk** [comment]
I'm not sure what version of the extension is running on your device, but the problem didn't happen on mine. By the way, the latest version now publicly available is v3.8.0.

![image](https://github.com/Frederisk/Wikitext-VSCode-Extension/assets/29837738/9463151b-d7c7-4ed3-8430-85702b1e5a3e)

> ... which must be at the start of a line to be interpreted as a table.

This [has been done](https://github.com/Frederisk/Wikitext-VSCode-Extension/blob/master/syntaxes/wikitext.tmLanguage.yaml#L378-L382) a long time ago.

**Comment by Frederisk** [comment]
It's weird. I'm using an Insiders v1.79.0 of VSCode, and I can't reproduce this issue. This looks more like some sort of issue with VSCode.

**Comment by jwfxpr** [comment]
Oh that's interesting. I'm using the current stable vscode, 1.78.2.

I guess we wait and see if the 1.79 fixes the behaviour. I'll try to update this issue then either way, with a much more definite reproducable example if necessary. 😊

Thanks for taking the time to look into it!

**Comment by jwfxpr** [comment]
With a little further investigation, I've tracked this down to an unexpected interaction with another extension! Sorry for the confusion and thanks again for the time spent.
