### ISSUE TITLE
Disable edit section links in preview

### ISSUE THREAD

**Issue by siddharthvp** [Frederisk/Wikitext-VSCode-Extension#8]
Thanks for developing this great extension!

I see the [edit] section links in the previews are quite bigger than what they are on the live sites. 

Since these links are useless and don't point point anywhere, it would be good to be able to hide these. [API:Parse](https://www.mediawiki.org/wiki/API:Parsing_wikitext) has a handy `disableeditsection` parameter. I think this parameter should always be used, but it would also be fine to make that a user preference. Thanks!

**Comment by Frederisk** [comment]
Thank you for your help! This issue will be resolved later.

**Comment by Frederisk** [comment]
I asked some users for their opinions. Many people said that they didn’t care about it, while others seemed to tend to be turned off. Few people said they wanted to keep it displayed.

I will try to set the `disableeditsection` setting to always on. If there are other editors who want it to be visible, then provide a toggle switch.

The reason I chose this way is that I don’t want the expansion to have too many options that would distract users.

Do you have any other ideas about this?

**Comment by siddharthvp** [comment]
> I will try to set the disableeditsection setting to always on. If there are other editors who want it to be visible, then provide a toggle switch.

This sounds pretty good to me.
