### ISSUE TITLE
Categories not shown

### ISSUE THREAD

**Issue by siddharthvp** [Frederisk/Wikitext-VSCode-Extension#9]
I see that categories are not shown in the previews. These can be shown by using `prop=text|categorieshtml` in the API:Parse request (and then concatenating the two pieces of HTML in the response).

**Comment by Frederisk** [comment]
This feature has been added. The categories will be displayed at the bottom of the page, which is separated by a `<hr />` tag.

**Comment by Frederisk** [comment]
The changes will be visible in the next version.😸

**Comment by Frederisk** [comment]
It's available now, update version 3.2.0 to enjoy it.
