### ISSUE TITLE
I want to change the name "API" on Preview Title to pageTitle in my [PAGE_INFO] code

### ISSUE THREAD

**Issue by duongnotnhan** [Frederisk/Wikitext-VSCode-Extension#91]
![image](https://github.com/user-attachments/assets/bcb4f4e6-e7a7-44ca-9702-183cc70a0fb1)
![image](https://github.com/user-attachments/assets/4461488f-58eb-4f54-a4bd-0e4c18e80035)
Just like:
```
WikitextPreviewer: <span class="mw-page-title-main">(pageTitle)</span>
```
I want to test my template on preview page:
![image](https://github.com/user-attachments/assets/c2f72d27-d062-41e5-a3f3-bbd7653c5fe3)
"API" must be pageTitle (I make sure the Template runs correctly on the official wiki page)

**Comment by Frederisk** [comment]
I think this is an acceptable change, but it should be noted that this API may currently have some strange problems, such as the following query may not obtain the expected results:

<https://en.wikipedia.org/w/api.php?action=parse&text={break{DISPLAYTITLE:test%20page|noerror}magic%20word}&title=Test%20page>

```ini
"displaytitle": "<span class=\"mw-page-title-main\">Test page</span>"
```

<https://en.wikipedia.org/w/api.php?action=parse&text={{DISPLAYTITLE:test%20page|noerror}}&title=Test%20page>

```ini
"displaytitle": "test page"
```

This is a [known upstream issue in phab](https://phabricator.wikimedia.org/T316424).

**Comment by Frederisk** [comment]
Since it's probably an [upstream issue from VSCode](https://github.com/microsoft/vscode-test-web/issues/128) that causes CI to always timeout and fail, I'll confirm that.
