### ISSUE TITLE
Previewer not loading all media on VSCode

### ISSUE THREAD

**Issue by MoonnShade** [Frederisk/Wikitext-VSCode-Extension#95]
Hi,

When using the preview function of this extension, the preview page is only loading the first 3 media files.
All other files below the first 3 on the page display as empty space. You can still click them if the have links, for example, but they do not show the media itself.

Example:

 First media file (video)
![imagem](https://github.com/user-attachments/assets/06abc79b-c267-4e67-ac84-9ff3c1a7e807)

Code:
![imagem](https://github.com/user-attachments/assets/296c0bde-7f70-42ae-8902-46a10f6666b5)

4th media file (image)
![imagem](https://github.com/user-attachments/assets/7eca9597-57c1-42ca-9049-f65f927b0dbc)

Code:
![imagem](https://github.com/user-attachments/assets/67fa721a-3043-40dc-83ec-300c18e94543)

Is this a known issue with VSCode or the extension? Is there a known fix or limitation?

Thanks for the help

**Comment by Frederisk** [comment]
If possible, could you tell me the address of the host website?

**Comment by MoonnShade** [comment]
> If possible, could you tell me the address of the host website?

Yep! This is the host: otogi.fandom.com

(The website link would be: https://otogi.fandom.com/ )

**Comment by Frederisk** [comment]
This link will use the API to convert four images to HTML: <https://otogi.fandom.com/api.php?action=parse&contentmodel=wikitext&text=[[File:With%20Toka]][[File:With%20Toka]][[File:With%20Toka]][[File:With%20Toka]]&format=xmlfm>

Obviously, there is something wrong with the content of the fourth picture:

```html
<img
src="data:image/gif;base64,R0lGODlhAQABAIABAAAAAP///yH5BAEAAAEALAAAAAABAAEAQAICTAEAOw%3D%3D"
.../>
```

I'm not sure if this is a bug from this site or from MediaWiki, but it's certainly an upstream issue. I may need to spend some time investigating it, or if possible you could contact the technical administrator of this site to confirm if any MediaWiki Extension is causing the problem.
